[package]
name = "pgr"
version = "0.1.0"
authors = ["Eugene Marcotte <emarcotte@gmail.com>"]
edition = "2018"

[dependencies]
users = "0.9.1"
terminal_size = "0.1.8"
getopts = "0.2"
unicode-width = "0.1.5"
